create table IF NOT EXISTS users (
id integer generated by default as identity,
is_deleted boolean default false,
tokens integer,
full_name varchar(255) not null,
password varchar(255) not null,
role varchar(255) not null,
primary key (id)
)